; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.3.10 on Fri Dec 10 2021 21:27:52 GMT+0100 (Mitteleuropäische Normalzeit)

