; tfree1.g
; called when tool 1 is freed
;
; generated by RepRapFirmware Configuration Tool v3.3.10 on Fri Dec 10 2021 21:27:52 GMT+0100 (Mitteleuropäische Normalzeit)

M83 ; relative extruder movement
G1 E-2 F3600 ; retract 2mm
M106 S0           ; turn off our print cooling fan
G91 ; relative axis movement
G1 Z3 F500 ; up 3mm
G90 ; absolute axis movement
G1 H1 U351.80 F6000 ; park the U carriage at 0mm