; pause.g
; called when a print from SD card is paused
;
; generated by RepRapFirmware Configuration Tool v3.3.10 on Fri Dec 10 2021 21:27:52 GMT+0100 (Mitteleuropäische Normalzeit)
M83            ; relative extruder moves
G1 E-10 F3600  ; retract 10mm of filament
G91            ; relative positioning
G1 Z5 F360     ; lift Z by 5mm
G90            ; absolute positioning
G1 H1 X-51.8 U351.8 F6000 ; park both heads
