; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.3.10 on Fri Dec 10 2021 21:27:51 GMT+0100 (Mitteleuropäische Normalzeit)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


